### ISSUE TITLE
역할 분담

### ISSUE THREAD

**Issue by HGU-Yangsijun** [Jun-Duo/Jun-Duo-Project#3]
역할 분담을 어떻게 하면 좋을까?

**Comment by AnJunYong02** [comment]
CRUD함수 구현하는 부분이랑 Main에서 실행하는 부분을 나눠서 구현하자.!

**Comment by AnJunYong02** [comment]
.c 파일을 두개를 만들자는 뜻!

**Comment by HGU-Yangsijun** [comment]
그럼 내가 CRUD 함수 쪽 구현하고
네가 main이랑 파일 입출력 구현하는 걸로 하자

**Comment by AnJunYong02** [comment]
오케이 굿
