### ISSUE TITLE
함수 구현 idea

### ISSUE THREAD

**Issue by AnJunYong02** [Jun-Duo/Jun-Duo-Project#4]
일단 CRUD, 파일 저장, 읽어오기랑 검색기능을 기본적으로 구현하자

**Comment by AnJunYong02** [comment]
꽉 찬 시트는 제외하여 보여주는 함수(선택할 수 있는 시트만 출력하는 함수)

**Comment by HGU-Yangsijun** [comment]
검색 기능 함수도 여러 가지로 나눌 수 있겠다.
예약자 이름, 예약 날짜 및 시간
