### ISSUE TITLE
R(Read 함수) 구현

### ISSUE THREAD

**Issue by AnJunYong02** [Jun-Duo/Jun-Duo-Project#7]
void ReadReseveration (reserve *p[20], int count)

**Comment by HGU-Yangsijun** [comment]
void ReadReservation (reserve *p[20], int count)

**Comment by HGU-Yangsijun** [comment]
void ReadReservation (Reserve *p[20], int count)

**Comment by HGU-Yangsijun** [comment]
void ReadReservation (Reserve p)

**Comment by HGU-Yangsijun** [comment]
목록 읽는 함수
void ListReservation (Reserve *r[], int count)
